### ISSUE TITLE
Plugin breaks when meta option is provided

### ISSUE THREAD

**Issue by LKay** [KnisterPeter/html-webpack-exclude-empty-assets-plugin#1]
When `html-webpack-plugin` config contains `meta` parameters this plugin tries to iterate through inserted `<meta/>` tags and since they don't have `src` or `href` attributes filtering function throws an error while calling `substr` on `undefined value`.

This needs to change to handle case when iterated tag is not asset-like:
https://github.com/KnisterPeter/html-webpack-exclude-empty-assets-plugin/blob/20670b73a66bacd23b1908a2f1e829fbe55d708f/index.js#L23-L27

Probably same thing could happen for `body`.

**Comment by KnisterPeter** [comment]
Thanks for reporting

**Comment by KnisterPeter** [comment]
@LKay Released as 0.1.1
