### ISSUE TITLE
Out-of-date?

### ISSUE THREAD

**Issue by rowild** [KnisterPeter/html-webpack-exclude-empty-assets-plugin#3]
When running webpack, this error gets thrown:

`Error: Plugin could not be registered at 'html-webpack-plugin-alter-asset-tags'. Hook was not found.`

It seems that the htmlWebpackPlugin api changed and this plugin needs to be adapted?
Are there any plans to do so?

**Comment by KnisterPeter** [comment]
Hi @rowild,
I'm not using this currently so I have no plans to update it anytime soon, but you could provide a PR if you don't mind.

**Comment by KnisterPeter** [comment]
I'll only update the dependencies and add prettier

**Comment by rowild** [comment]
I tried to fix it, but I am incapable of it. However, it seems there is a successor plugin that can be used in-place of this one.

**Comment by davidejones** [comment]
I encountered a similar problem @rowild what plugin did you use in place of this one?

I tried to fix the issue in a PR here https://github.com/KnisterPeter/html-webpack-exclude-empty-assets-plugin/pull/9 feel free to try it out

**Comment by KnisterPeter** [comment]
Released as 0.1.4
